google_sheets:
  csv_url: "https://docs.google.com/spreadsheets/d/1c2QmtlaBNsQ32j7JWly-ayigbkmfireBUisUEzxaJTY/export?format=csv&gid=561406276"

player_ids:
  - "136432206"

selenium:
  url: "https://ks-giftcode.centurygame.com"
  wait_time: 2

selectors:
  player_id_input: '//*[@id="playerIdInput"]'
  login_button: '//*[@id="loginButton"]'
  gift_code_input: '//*[@id="giftCodeInput"]'
  confirm_button: '//*[@id="confirmButton"]'
``
