name: Auto Gift

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable # 특정 버전보다는 stable로 유지

      - name: Install dependencies
        run: |
          pip install undetected-chromedriver selenium requests

      - name: Run script with Display
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          sudo apt-get update
          # 필수 라이브러리 및 xvfb 설치
          sudo apt-get install -y xvfb libgbm-dev libnss3 libatk-bridge2.0-0 libgtk-3-0
          
          # xvfb-run을 통해 가상 디스플레이에서 실행
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python main.py

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update used_codes.json"
          file_pattern: 'used_codes.json'

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
