name: Auto Gift

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 🔥 Chrome 설치
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # 🔥 Chrome 버전 확인 (중요)
      - name: Check Chrome version
        run: google-chrome --version

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      # 🔥 스크린샷 업로드
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "*.png"
